### ISSUE TITLE
After harmonisation, if file could not be harmonised, produce a short report to explain why 

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-harmoniser#24]
A text file reporting that a file could not be harmonised should be produced and published on the ftp under /harmonised to inform users that this study has been attempted but could not be harmonised for reasons explained.

**Comment by jdhayhurst** [comment]
Additional suggestion from OTAR: it's pretty common that all rows fail to harmonise, and in that case it would be better to conclude that the study can't be harmonised, and not put it in the harmonised table (and not share harmonised sumstats). Currently they will be there but have NA for all the harmonised data.
e.g. 
GCST010771
GCST90011898
GCST90027272
GCST90017148

How does this sound @ljwh2? 
If there is at least one row with harmonised data we can share, otherwise report it as unharmonisable

**Comment by jdhayhurst** [comment]
That is precisely the issue

**Comment by aoifemcm** [comment]
Plus one for this request, having this logging file would help immensely.

**Comment by ljwh2** [comment]
Discussed with @buniello, simplest solution would be to produce a file that states "Harmonisation not possible for this file. For more information about the harmonisation process, see https://www.ebi.ac.uk/gwas/docs/methods/summary-statistics". This would satisfy the user who wants to know whether the file was attempted for harmonisation and failed, or had not yet been attempted for harmonisation. This should be produced for (instead of?) the files that contain only a header or NA for all rows.

**Comment by ljwh2** [comment]
@jiyue1214 @aoifemcm could you possibly provide an example of the log file the new harmonisation file produces?

**Comment by aoifemcm** [comment]
We've discussed adding more information in the log file 
e.g. x number of sites were harmonised (hm_codes 1-13), y number not harmonised (hm_codes 14-18). If y = total number of sites, the conclusion is the whole file cannot be harmonised, and a 'harmonisation failed' message could be added. In that case I guess you wouldn't want the actual empty 'harmonised' data file to be moved to the ftp, just the log file.

Something to consider is how much time/compute it would take to do the counts of the hm_codes, and if a lot, if there's an alternative for assessing that the full file was not harmonised.

We also planned to improve the text of the log file to be more meaningful. e.g. Direction of palindromic SNPs inferred as forward by establishing consensus direction of 10 percent of all sites. 10_percent forward ratio = 0.99999
or Direction of palindromic SNPs inferred as forward by establishing consensus direction of all sites. All sites forward ratio = 0.99999
(Remember this is one of the changes Yue made to the pipeline, originally the direction of all sites was checked first to infer consensus orientation, we dropped this to inferring direction from 10% of sites. If the direction of 10% is below a threshold the pipeline checks direction of all sites.  We wanted this to be tracked.)

**Comment by jiyue1214** [comment]
Hi, Laura

1. Here is an example of the current log file. The current log file only contains (the forward sites ratio, the reference source, and the dbSNP version). We plan to add more information to this log file.
<img width="928" alt="Screenshot 2022-05-05 at 14 38 06" src="https://user-images.githubusercontent.com/52689284/166948843-c73e10e3-6ef5-49ca-a8d4-f25ec849cbcb.png">

2. I quickly checked the four studies mentioned above (GCST010771, GCST90011898, GCST90027272, GCST90017148). I found they cannot be harmonized because these data do not have effect _allele and( or) other_allele information. I show their formatted data details in this table:
<img width="1173" alt="Screenshot 2022-05-05 at 15 37 59" src="https://user-images.githubusercontent.com/52689284/166949190-69433788-c2eb-487f-ae30-0fff0b69e405.png">
All sites in the file can be processed by our pipeline without any errors, just give hm_14 to show that required fields (Chr, pos, effect_allele, and other_allele) are not known.

3. hm_code can tell us the reason why they are not harmonized. It is easy to add a hm_code report in the current log file to show the number of sites of each harmonization code.

**Comment by jiyue1214** [comment]
@ljwh2 Here are four examples of our modified log files.
Example 1: All sites in the file failed in harmonization, and there is a flag "FLAG_FAILED_HARMONIZATION" in the log file. 
![Screenshot 2022-05-13 at 13 31 43](https://user-images.githubusercontent.com/52689284/168284523-81e9d37c-19a4-4682-bcd0-2186b8f9a063.png)

Example 2: The file has been harmonized, and palindromic SNPs' direction cannot be inferred.
![Screenshot 2022-05-13 at 13 31 15](https://user-images.githubusercontent.com/52689284/168284561-ca789c68-61e4-4d9d-afa4-13e0a6712379.png)

Example 3: The file has been harmonized, and the direction of palindromic SNPs is inferred as forward by establishing a consensus direction of all sites
![Screenshot 2022-05-13 at 13 30 54](https://user-images.githubusercontent.com/52689284/168284607-6cc3fcfb-0d96-4bb3-b18f-049e2a01f752.png)

Example 4:The file has been harmonized, and the direction of palindromic SNPs is inferred as forward by establishing a consensus direction of 10% percent of all sites
![Screenshot 2022-05-13 at 13 30 34](https://user-images.githubusercontent.com/52689284/168284684-2c4f8e7f-928b-4237-a945-6ad8e569c23c.png)

**Comment by ljwh2** [comment]
@jiyue1214 I think this looks great and very clear to the user. One suggestion would be to add a decimal place to the % of sites harmonised so we are less likely to get this situation where we say "0% of sites failed to harmonise" and then list some failures. I'm guessing this comes up quite a lot, when the % thats fail to harmonise is quite small but not = 0.

**Comment by buniello** [comment]
I agree, it looks good!

**Comment by ljwh2** [comment]
Discussed with @aoifemcm, could also include:
- version of pipeline
- date harmonisation was run
- logfile name should include GCST, this should be already available at time of harmonisation - @jdhayhurst to advise
